version: "3.7"

services:
  radarr:
    image: "linuxserver/radarr:latest"
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./Movies/:/movies
      - ./.config/radarr:/config
      - ./.downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./Series/:/tv
      - ./.config/sonarr:/config
      - ./.downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    volumes:
      - ./Movies:/media/Movies
      - ./Series:/media/Series
      - ./.config/jellyfin:/config
      - ./.cache/jellyfin:/cache
    ports:
      - 8096:8096
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - WEBUI_PORT=8080
    volumes:
      - ./.config/qbit:/config
      - ./.downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - AUTO_UPDATE=true #optional
    volumes:
      - ./.config/jackett:/config
      - /dev/null:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Brussels
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  # Nginx to use user friendly urls (example.local/jellyfin -> example.local:8096)
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 80:80  # Default http goes to nginx
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    privileged: true
    restart: unless-stopped
    volumes:
      - ./.config/ha:/config
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    image: 'ghcr.io/home-assistant/home-assistant:stable'
